In [2]:
import pandas as pd

In [ ]:
df = pd.read_csv("gapminder_data_graphs.csv") # Tabular Data

In [5]:
df

,country,continent,year,life_exp,hdi_index,co2_consump,gdp,services
0,Afghanistan,Asia,1998,53.3,0.344,0.0522,NaN,24.4
1,Afghanistan,Asia,1999,54.7,0.348,0.0402,NaN,24.6
2,Afghanistan,Asia,2000,54.7,0.350,0.0370,NaN,24.7
3,Afghanistan,Asia,2001,54.8,0.353,0.0376,NaN,24.7
4,Afghanistan,Asia,2002,55.5,0.384,0.0471,333.0,25.6
...,...,...,...,...,...,...,...,...
3670,Zimbabwe,Africa,2014,58.0,0.547,0.8810,1440.0,25.4
3671,Zimbabwe,Africa,2015,58.6,0.553,0.8810,1450.0,25.7
3672,Zimbabwe,Africa,2016,59.2,0.558,0.7710,1430.0,26.1
3673,Zimbabwe,Africa,2017,59.9,0.563,0.8450,1480.0,26.6
3674,Zimbabwe,Africa,2018,60.6,0.569,0.8500,1510.0,27.2

In [6]:
type(df)

pandas.DataFrame

In [ ]:
df["country"] # to get the country from dictionary

0       Afghanistan
1       Afghanistan
2       Afghanistan
3       Afghanistan
4       Afghanistan
           ...
3670       Zimbabwe
3671       Zimbabwe
3672       Zimbabwe
3673       Zimbabwe
3674       Zimbabwe
Name: country, Length: 3675, dtype: str

In [ ]:
type(df["country"]) 
# dataframe is matrix like something
# series is 1 D vector like something

pandas.Series

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3675 entries, 0 to 3674
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   country      3675 non-null   str
 1   continent    3675 non-null   str
 2   year         3675 non-null   int64
 3   life_exp     3675 non-null   float64
 4   hdi_index    3563 non-null   float64
 5   co2_consump  3671 non-null   float64
 6   gdp          3633 non-null   float64
 7   services     3675 non-null   float64
dtypes: float64(5), int64(1), str(2)
memory usage: 229.8 KB

In [12]:
# Top 5 Element
df.head()
# Top 15 Element
df.head(15)

,country,continent,year,life_exp,hdi_index,co2_consump,gdp,services
0,Afghanistan,Asia,1998,53.3,0.344,0.0522,NaN,24.4
1,Afghanistan,Asia,1999,54.7,0.348,0.0402,NaN,24.6
2,Afghanistan,Asia,2000,54.7,0.350,0.0370,NaN,24.7
3,Afghanistan,Asia,2001,54.8,0.353,0.0376,NaN,24.7
4,Afghanistan,Asia,2002,55.5,0.384,0.0471,333.0,25.6
5,Afghanistan,Asia,2003,56.5,0.393,0.0509,346.0,25.9
6,Afghanistan,Asia,2004,57.1,0.409,0.0368,336.0,26.1
7,Afghanistan,Asia,2005,57.6,0.418,0.0515,360.0,26.5
8,Afghanistan,Asia,2006,58.0,0.429,0.0622,368.0,26.9
9,Afghanistan,Asia,2007,58.5,0.447,0.0838,409.0,27.7
10,Afghanistan,Asia,2008,59.2,0.447,0.1520,415.0,28.2
11,Afghanistan,Asia,2009,59.9,0.460,0.2380,492.0,29.5
12,Afghanistan,Asia,2010,60.5,0.472,0.2900,547.0,30.7
13,Afghanistan,Asia,2011,61.0,0.477,0.4060,533.0,31.7
14,Afghanistan,Asia,2012,61.4,0.489,0.3450,580.0,32.8

In [ ]:
#Top 15 bottom
df.tail(15)

,country,continent,year,life_exp,hdi_index,co2_consump,gdp,services
3660,Zimbabwe,Africa,2004,46.4,0.411,0.785,1210.0,26.2
3661,Zimbabwe,Africa,2005,46.8,0.411,0.887,1140.0,25.8
3662,Zimbabwe,Africa,2006,47.4,0.414,0.853,1090.0,25.4
3663,Zimbabwe,Africa,2007,48.2,0.421,0.803,1040.0,25.2
3664,Zimbabwe,Africa,2008,48.9,0.422,0.624,850.0,24.4
3665,Zimbabwe,Africa,2009,50.2,0.458,0.441,941.0,24.8
3666,Zimbabwe,Africa,2010,52.3,0.482,0.607,1110.0,25.2
3667,Zimbabwe,Africa,2011,54.4,0.499,0.737,1250.0,25.0
3668,Zimbabwe,Africa,2012,56.0,0.525,0.587,1430.0,25.4
3669,Zimbabwe,Africa,2013,57.2,0.537,0.872,1440.0,25.3
3670,Zimbabwe,Africa,2014,58.0,0.547,0.881,1440.0,25.4
3671,Zimbabwe,Africa,2015,58.6,0.553,0.881,1450.0,25.7
3672,Zimbabwe,Africa,2016,59.2,0.558,0.771,1430.0,26.1
3673,Zimbabwe,Africa,2017,59.9,0.563,0.845,1480.0,26.6
3674,Zimbabwe,Africa,2018,60.6,0.569,0.850,1510.0,27.2

In [ ]:
df.shape # rows and  columns

(3675, 8)

In [ ]:
df.describe() # work on numerical data

,year,life_exp,hdi_index,co2_consump,gdp,services
count,3675.000000,3675.000000,3563.000000,3671.000000,3633.000000,3675.000000
mean,2008.000000,69.849306,0.674864,4.712731,11966.053675,51.248705
std,6.056125,8.886563,0.164834,6.567435,17105.787953,18.312501
min,1998.000000,32.500000,0.255000,0.015900,238.000000,5.590000
25%,2003.000000,63.900000,0.537500,0.560500,1470.000000,37.600000
50%,2008.000000,71.700000,0.699000,2.250000,4280.000000,52.900000
75%,2013.000000,76.400000,0.805000,6.615000,13600.000000,65.700000
max,2018.000000,84.800000,0.956000,67.100000,105000.000000,88.500000

In [17]:
df.describe(include="object")

C:\Users\anura\AppData\Local\Temp\ipykernel_19540\702825166.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include="object")

            country continent
count          3675      3675
unique          175         6
top     Afghanistan    Africa
freq             21      1071

# Column Operation

In [ ]:
df.columns # know the Columns

Index(['country', 'continent', 'year', 'life_exp', 'hdi_index', 'co2_consump',
       'gdp', 'services'],
      dtype='str')

In [20]:
df.keys()

Index(['country', 'continent', 'year', 'life_exp', 'hdi_index', 'co2_consump',
       'gdp', 'services'],
      dtype='str')

# Specialized Dict

In [21]:
df["country"]

0       Afghanistan
1       Afghanistan
2       Afghanistan
3       Afghanistan
4       Afghanistan
           ...
3670       Zimbabwe
3671       Zimbabwe
3672       Zimbabwe
3673       Zimbabwe
3674       Zimbabwe
Name: country, Length: 3675, dtype: str

In [22]:
df[["country","continent"]]

          country continent
0     Afghanistan      Asia
1     Afghanistan      Asia
2     Afghanistan      Asia
3     Afghanistan      Asia
4     Afghanistan      Asia
...           ...       ...
3670     Zimbabwe    Africa
3671     Zimbabwe    Africa
3672     Zimbabwe    Africa
3673     Zimbabwe    Africa
3674     Zimbabwe    Africa

[3675 rows x 2 columns]

In [ ]:
# Want all Unique country 
df["country"].unique()

<StringArray>
[         'Afghanistan',              'Albania',              'Algeria',
               'Angola',            'Argentina',              'Armenia',
            'Australia',              'Austria',           'Azerbaijan',
              'Bahamas',
 ...
 'United Arab Emirates',       'United Kingdom',        'United States',
              'Uruguay',           'Uzbekistan',              'Vanuatu',
              'Vietnam',                'Yemen',               'Zambia',
             'Zimbabwe']
Length: 175, dtype: str

In [ ]:
# How manytimes particular country appear
df["country"].value_counts() # This is Series 1st col is indexes or keys

country
Afghanistan    21
Albania        21
Algeria        21
Angola         21
Argentina      21
               ..
Vanuatu        21
Vietnam        21
Yemen          21
Zambia         21
Zimbabwe       21
Name: count, Length: 175, dtype: int64

In [25]:
df["country"].value_counts().index

Index(['Afghanistan', 'Albania', 'Algeria', 'Angola', 'Argentina', 'Armenia',
       'Australia', 'Austria', 'Azerbaijan', 'Bahamas',
       ...
       'United Arab Emirates', 'United Kingdom', 'United States', 'Uruguay',
       'Uzbekistan', 'Vanuatu', 'Vietnam', 'Yemen', 'Zambia', 'Zimbabwe'],
      dtype='str', name='country', length=175)

In [26]:
# Rename a col 
df.rename({"country":"Country"},axis=1)

,Country,continent,year,life_exp,hdi_index,co2_consump,gdp,services
0,Afghanistan,Asia,1998,53.3,0.344,0.0522,NaN,24.4
1,Afghanistan,Asia,1999,54.7,0.348,0.0402,NaN,24.6
2,Afghanistan,Asia,2000,54.7,0.350,0.0370,NaN,24.7
3,Afghanistan,Asia,2001,54.8,0.353,0.0376,NaN,24.7
4,Afghanistan,Asia,2002,55.5,0.384,0.0471,333.0,25.6
...,...,...,...,...,...,...,...,...
3670,Zimbabwe,Africa,2014,58.0,0.547,0.8810,1440.0,25.4
3671,Zimbabwe,Africa,2015,58.6,0.553,0.8810,1450.0,25.7
3672,Zimbabwe,Africa,2016,59.2,0.558,0.7710,1430.0,26.1
3673,Zimbabwe,Africa,2017,59.9,0.563,0.8450,1480.0,26.6
3674,Zimbabwe,Africa,2018,60.6,0.569,0.8500,1510.0,27.2

In [27]:
df

,country,continent,year,life_exp,hdi_index,co2_consump,gdp,services
0,Afghanistan,Asia,1998,53.3,0.344,0.0522,NaN,24.4
1,Afghanistan,Asia,1999,54.7,0.348,0.0402,NaN,24.6
2,Afghanistan,Asia,2000,54.7,0.350,0.0370,NaN,24.7
3,Afghanistan,Asia,2001,54.8,0.353,0.0376,NaN,24.7
4,Afghanistan,Asia,2002,55.5,0.384,0.0471,333.0,25.6
...,...,...,...,...,...,...,...,...
3670,Zimbabwe,Africa,2014,58.0,0.547,0.8810,1440.0,25.4
3671,Zimbabwe,Africa,2015,58.6,0.553,0.8810,1450.0,25.7
3672,Zimbabwe,Africa,2016,59.2,0.558,0.7710,1430.0,26.1
3673,Zimbabwe,Africa,2017,59.9,0.563,0.8450,1480.0,26.6
3674,Zimbabwe,Africa,2018,60.6,0.569,0.8500,1510.0,27.2

In [ ]:
# Rename a col 
df.rename({"country":"Country"},axis=1,inplace=True) # make change in original Dataframe

In [ ]:
df.country # attribute way of accessing  \\Not Recommanded

0       Afghanistan
1       Afghanistan
2       Afghanistan
3       Afghanistan
4       Afghanistan
           ...
3670       Zimbabwe
3671       Zimbabwe
3672       Zimbabwe
3673       Zimbabwe
3674       Zimbabwe
Name: country, Length: 3675, dtype: str

In [29]:
# How to drop particular column
df.drop("continent",axis=1)

          country  year  life_exp  hdi_index  co2_consump     gdp  services
0     Afghanistan  1998      53.3      0.344       0.0522     NaN      24.4
1     Afghanistan  1999      54.7      0.348       0.0402     NaN      24.6
2     Afghanistan  2000      54.7      0.350       0.0370     NaN      24.7
3     Afghanistan  2001      54.8      0.353       0.0376     NaN      24.7
4     Afghanistan  2002      55.5      0.384       0.0471   333.0      25.6
...           ...   ...       ...        ...          ...     ...       ...
3670     Zimbabwe  2014      58.0      0.547       0.8810  1440.0      25.4
3671     Zimbabwe  2015      58.6      0.553       0.8810  1450.0      25.7
3672     Zimbabwe  2016      59.2      0.558       0.7710  1430.0      26.1
3673     Zimbabwe  2017      59.9      0.563       0.8450  1480.0      26.6
3674     Zimbabwe  2018      60.6      0.569       0.8500  1510.0      27.2

[3675 rows x 7 columns]

In [30]:
df

,country,continent,year,life_exp,hdi_index,co2_consump,gdp,services
0,Afghanistan,Asia,1998,53.3,0.344,0.0522,NaN,24.4
1,Afghanistan,Asia,1999,54.7,0.348,0.0402,NaN,24.6
2,Afghanistan,Asia,2000,54.7,0.350,0.0370,NaN,24.7
3,Afghanistan,Asia,2001,54.8,0.353,0.0376,NaN,24.7
4,Afghanistan,Asia,2002,55.5,0.384,0.0471,333.0,25.6
...,...,...,...,...,...,...,...,...
3670,Zimbabwe,Africa,2014,58.0,0.547,0.8810,1440.0,25.4
3671,Zimbabwe,Africa,2015,58.6,0.553,0.8810,1450.0,25.7
3672,Zimbabwe,Africa,2016,59.2,0.558,0.7710,1430.0,26.1
3673,Zimbabwe,Africa,2017,59.9,0.563,0.8450,1480.0,26.6
3674,Zimbabwe,Africa,2018,60.6,0.569,0.8500,1510.0,27.2

In [ ]:
# How to drop particular column
df.drop("continent",axis=1,inplace=True) # To make parmanent change

In [ ]:
# How to add the new column 
# add population*gdp_cap
df["total_gdp"] = df["gdp"]*1000

In [32]:
df

,country,continent,year,life_exp,hdi_index,co2_consump,gdp,services,total_gdp
0,Afghanistan,Asia,1998,53.3,0.344,0.0522,NaN,24.4,NaN
1,Afghanistan,Asia,1999,54.7,0.348,0.0402,NaN,24.6,NaN
2,Afghanistan,Asia,2000,54.7,0.350,0.0370,NaN,24.7,NaN
3,Afghanistan,Asia,2001,54.8,0.353,0.0376,NaN,24.7,NaN
4,Afghanistan,Asia,2002,55.5,0.384,0.0471,333.0,25.6,333000.0
...,...,...,...,...,...,...,...,...,...
3670,Zimbabwe,Africa,2014,58.0,0.547,0.8810,1440.0,25.4,1440000.0
3671,Zimbabwe,Africa,2015,58.6,0.553,0.8810,1450.0,25.7,1450000.0
3672,Zimbabwe,Africa,2016,59.2,0.558,0.7710,1430.0,26.1,1430000.0
3673,Zimbabwe,Africa,2017,59.9,0.563,0.8450,1480.0,26.6,1480000.0
3674,Zimbabwe,Africa,2018,60.6,0.569,0.8500,1510.0,27.2,1510000.0

In [34]:
df["custom"] = [i for i in range(3675)]

In [35]:
df

,country,continent,year,life_exp,hdi_index,co2_consump,gdp,services,total_gdp,custom
0,Afghanistan,Asia,1998,53.3,0.344,0.0522,NaN,24.4,NaN,0
1,Afghanistan,Asia,1999,54.7,0.348,0.0402,NaN,24.6,NaN,1
2,Afghanistan,Asia,2000,54.7,0.350,0.0370,NaN,24.7,NaN,2
3,Afghanistan,Asia,2001,54.8,0.353,0.0376,NaN,24.7,NaN,3
4,Afghanistan,Asia,2002,55.5,0.384,0.0471,333.0,25.6,333000.0,4
...,...,...,...,...,...,...,...,...,...,...
3670,Zimbabwe,Africa,2014,58.0,0.547,0.8810,1440.0,25.4,1440000.0,3670
3671,Zimbabwe,Africa,2015,58.6,0.553,0.8810,1450.0,25.7,1450000.0,3671
3672,Zimbabwe,Africa,2016,59.2,0.558,0.7710,1430.0,26.1,1430000.0,3672
3673,Zimbabwe,Africa,2017,59.9,0.563,0.8450,1480.0,26.6,1480000.0,3673
3674,Zimbabwe,Africa,2018,60.6,0.569,0.8500,1510.0,27.2,1510000.0,3674

In [36]:
df.drop(["custom","total_gdp"],axis=1,inplace=True)

In [37]:
df

,country,continent,year,life_exp,hdi_index,co2_consump,gdp,services
0,Afghanistan,Asia,1998,53.3,0.344,0.0522,NaN,24.4
1,Afghanistan,Asia,1999,54.7,0.348,0.0402,NaN,24.6
2,Afghanistan,Asia,2000,54.7,0.350,0.0370,NaN,24.7
3,Afghanistan,Asia,2001,54.8,0.353,0.0376,NaN,24.7
4,Afghanistan,Asia,2002,55.5,0.384,0.0471,333.0,25.6
...,...,...,...,...,...,...,...,...
3670,Zimbabwe,Africa,2014,58.0,0.547,0.8810,1440.0,25.4
3671,Zimbabwe,Africa,2015,58.6,0.553,0.8810,1450.0,25.7
3672,Zimbabwe,Africa,2016,59.2,0.558,0.7710,1430.0,26.1
3673,Zimbabwe,Africa,2017,59.9,0.563,0.8450,1480.0,26.6
3674,Zimbabwe,Africa,2018,60.6,0.569,0.8500,1510.0,27.2

# Rows Operations

In [41]:
ser = df["country"]
ser

0       Afghanistan
1       Afghanistan
2       Afghanistan
3       Afghanistan
4       Afghanistan
           ...
3670       Zimbabwe
3671       Zimbabwe
3672       Zimbabwe
3673       Zimbabwe
3674       Zimbabwe
Name: country, Length: 3675, dtype: str

In [ ]:
#indexing
ser[5]

'Afghanistan'

In [42]:
# Slicing
ser[4:16]

4     Afghanistan
5     Afghanistan
6     Afghanistan
7     Afghanistan
8     Afghanistan
9     Afghanistan
10    Afghanistan
11    Afghanistan
12    Afghanistan
13    Afghanistan
14    Afghanistan
15    Afghanistan
Name: country, dtype: str

In [43]:
ser.index

RangeIndex(start=0, stop=3675, step=1)

In [44]:
import numpy as np 
ser.index = np.arange(1,df.shape[0]+1,1)

In [45]:
ser

1       Afghanistan
2       Afghanistan
3       Afghanistan
4       Afghanistan
5       Afghanistan
           ...
3671       Zimbabwe
3672       Zimbabwe
3673       Zimbabwe
3674       Zimbabwe
3675       Zimbabwe
Name: country, Length: 3675, dtype: str

# Implicit and Explicit Indices

In [47]:
# Provided from outside  => Explicit Indices/ Row Label
# Already Present => Implicit Indices always start from 0

In [ ]:
ser.index[1] # Beacause everything increment by 1 using explicit Indexes

np.int64(2)

In [ ]:
data = pd.Series(["a","b","c"],index=[1,5,3])
data #1 5 3 is label

1    a
5    b
3    c
dtype: str

In [ ]:
data[1]
data[1:3] # Slicing byDefault Using Implicit Indexing or Positional Indices

5    b
3    c
dtype: str

In [52]:
data = pd.Series(["a","b","c"],index=["x","y","z"])

In [53]:
data

x    a
y    b
z    c
dtype: str

In [55]:
data[:1]

x    a
dtype: str

In [56]:
data["x"]

'a'