In [7]:
import pandas as pd
import numpy as np

In [18]:
movies = pd.read_csv("movies.csv")
directors = pd.read_csv("directors.csv")

In [19]:
movies

,Unnamed: 0,id,budget,popularity,revenue,title,vote_average,vote_count,director_id,year,month,day
0,0,43597,237000000,150,2787965087,Avatar,7.2,11800,4762,2009,Dec,Thursday
1,1,43598,300000000,139,961000000,Pirates of the Caribbean: At World's End,6.9,4500,4763,2007,May,Saturday
2,2,43599,245000000,107,880674609,Spectre,6.3,4466,4764,2015,Oct,Monday
3,3,43600,250000000,112,1084939099,The Dark Knight Rises,7.6,9106,4765,2012,Jul,Monday
4,5,43602,258000000,115,890871626,Spider-Man 3,5.9,3576,4767,2007,May,Tuesday
...,...,...,...,...,...,...,...,...,...,...,...,...
1460,4736,48363,0,3,321952,The Last Waltz,7.9,64,4809,1978,May,Monday
1461,4743,48370,27000,19,3151130,Clerks,7.4,755,5369,1994,Sep,Tuesday
1462,4748,48375,0,7,0,Rampage,6.0,131,5148,2009,Aug,Friday
1463,4749,48376,0,3,0,Slacker,6.4,77,5535,1990,Jul,Friday
1464,4768,48395,220000,14,2040920,El Mariachi,6.6,238,5097,1992,Sep,Friday

In [21]:
directors.head()

   Unnamed: 0      director_name    id gender
0           0      James Cameron  4762   Male
1           1     Gore Verbinski  4763   Male
2           2         Sam Mendes  4764   Male
3           3  Christopher Nolan  4765   Male
4           4     Andrew Stanton  4766   Male

In [28]:
a = pd.DataFrame({'A':[10,30],'B':[20,40]})
b = pd.DataFrame({'A':[10,30],'C':[20,40]})

In [30]:
a

    A   B
0  10  20
1  30  40

In [31]:
b

    A   C
0  10  20
1  30  40

In [29]:
pd.concat([a,b],axis=0)

    A     B     C
0  10  20.0   NaN
1  30  40.0   NaN
0  10   NaN  20.0
1  30   NaN  40.0

In [27]:
pd.concat([a,b],axis=1)

    A   B   A   C
0  10  20  10  20
1  20  30  20  30

In [32]:
pd.concat([a,b],keys=["x","y"]).loc["x"]

    A     B   C
0  10  20.0 NaN
1  30  40.0 NaN

In [34]:
# inner connection
pd.concat([a,b],axis=0,join="inner")

    A
0  10
1  30
0  10
1  30

In [35]:
# Merge = Join Side by Side

In [ ]:
users = pd.DataFrame({'userid':[1,2,3],'name':['A','B','C']})
msgs = pd.DataFrame({'userid':[1,1,2],'msg':['hello','bye','hi']})

In [37]:
users

   userid name
0       1    A
1       2    B
2       3    C

In [38]:
msgs

   userid    msg
0       1  hello
1       1    bye
2       2     hi

In [ ]:
pd.concat([users,msgs],axis=1) # What's that ?

   userid name  userid    msg
0       1    A       1  hello
1       2    B       1    bye
2       3    C       2     hi

In [41]:
msgs.merge(users,on="userid")

   userid    msg name
0       1  hello    A
1       1    bye    A
2       2     hi    B

In [42]:
users = pd.DataFrame({'userid':[1,2,3],'name':['A','B','C']})
msgs = pd.DataFrame({'userid':[1,1,2],'msg':['hello','bye','hi']})

In [ ]:
users.rename(columns={"userid":"id"},inplace=True)
users

   id name
0   1    A
1   2    B
2   3    C

In [45]:
msgs

   userid    msg
0       1  hello
1       1    bye
2       2     hi

In [46]:
users.merge(msgs,left_on="id",right_on="userid")

   id name  userid    msg
0   1    A       1  hello
1   1    A       1    bye
2   2    B       2     hi

In [47]:
# inner,outer,left,right

In [ ]:
users.merge(msgs,left_on="id",right_on="userid",how="inner")

   id name  userid    msg
0   1    A       1  hello
1   1    A       1    bye
2   2    B       2     hi

In [49]:
users.merge(msgs,left_on="id",right_on="userid",how="outer")

   id name  userid    msg
0   1    A     1.0  hello
1   1    A     1.0    bye
2   2    B     2.0     hi
3   3    C     NaN    NaN

In [50]:
users.merge(msgs,left_on="id",right_on="userid",how="left")

   id name  userid    msg
0   1    A     1.0  hello
1   1    A     1.0    bye
2   2    B     2.0     hi
3   3    C     NaN    NaN

In [51]:
users.merge(msgs,left_on="id",right_on="userid",how="right")

   id name  userid    msg
0   1    A       1  hello
1   1    A       1    bye
2   2    B       2     hi

In [52]:
movies

,Unnamed: 0,id,budget,popularity,revenue,title,vote_average,vote_count,director_id,year,month,day
0,0,43597,237000000,150,2787965087,Avatar,7.2,11800,4762,2009,Dec,Thursday
1,1,43598,300000000,139,961000000,Pirates of the Caribbean: At World's End,6.9,4500,4763,2007,May,Saturday
2,2,43599,245000000,107,880674609,Spectre,6.3,4466,4764,2015,Oct,Monday
3,3,43600,250000000,112,1084939099,The Dark Knight Rises,7.6,9106,4765,2012,Jul,Monday
4,5,43602,258000000,115,890871626,Spider-Man 3,5.9,3576,4767,2007,May,Tuesday
...,...,...,...,...,...,...,...,...,...,...,...,...
1460,4736,48363,0,3,321952,The Last Waltz,7.9,64,4809,1978,May,Monday
1461,4743,48370,27000,19,3151130,Clerks,7.4,755,5369,1994,Sep,Tuesday
1462,4748,48375,0,7,0,Rampage,6.0,131,5148,2009,Aug,Friday
1463,4749,48376,0,3,0,Slacker,6.4,77,5535,1990,Jul,Friday
1464,4768,48395,220000,14,2040920,El Mariachi,6.6,238,5097,1992,Sep,Friday

In [53]:
directors

      Unnamed: 0      director_name    id gender
0              0      James Cameron  4762   Male
1              1     Gore Verbinski  4763   Male
2              2         Sam Mendes  4764   Male
3              3  Christopher Nolan  4765   Male
4              4     Andrew Stanton  4766   Male
...          ...                ...   ...    ...
2344        2344      Shane Carruth  7106   Male
2345        2345   Neill Dela Llana  7107    NaN
2346        2346        Scott Smith  7108    NaN
2347        2347        Daniel Hsia  7109   Male
2348        2348   Brian Herzlinger  7110   Male

[2349 rows x 4 columns]

In [ ]:
movies = pd.read_csv("movies.csv",index_col=0)

In [55]:
movies

,id,budget,popularity,revenue,title,vote_average,vote_count,director_id,year,month,day
0,43597,237000000,150,2787965087,Avatar,7.2,11800,4762,2009,Dec,Thursday
1,43598,300000000,139,961000000,Pirates of the Caribbean: At World's End,6.9,4500,4763,2007,May,Saturday
2,43599,245000000,107,880674609,Spectre,6.3,4466,4764,2015,Oct,Monday
3,43600,250000000,112,1084939099,The Dark Knight Rises,7.6,9106,4765,2012,Jul,Monday
5,43602,258000000,115,890871626,Spider-Man 3,5.9,3576,4767,2007,May,Tuesday
...,...,...,...,...,...,...,...,...,...,...,...
4736,48363,0,3,321952,The Last Waltz,7.9,64,4809,1978,May,Monday
4743,48370,27000,19,3151130,Clerks,7.4,755,5369,1994,Sep,Tuesday
4748,48375,0,7,0,Rampage,6.0,131,5148,2009,Aug,Friday
4749,48376,0,3,0,Slacker,6.4,77,5535,1990,Jul,Friday
4768,48395,220000,14,2040920,El Mariachi,6.6,238,5097,1992,Sep,Friday

In [56]:
directors = pd.read_csv("directors.csv",index_col=0)

In [57]:
directors

          director_name    id gender
0         James Cameron  4762   Male
1        Gore Verbinski  4763   Male
2            Sam Mendes  4764   Male
3     Christopher Nolan  4765   Male
4        Andrew Stanton  4766   Male
...                 ...   ...    ...
2344      Shane Carruth  7106   Male
2345   Neill Dela Llana  7107    NaN
2346        Scott Smith  7108    NaN
2347        Daniel Hsia  7109   Male
2348   Brian Herzlinger  7110   Male

[2349 rows x 3 columns]

In [58]:
movies.shape

(1465, 11)

In [59]:
directors.shape

(2349, 3)

* left outer join to keep all movie and some directors

In [ ]:
movies["director_id"].unique()

array([4762, 4763, 4764, 4765, 4767, 4771, 4772, 4773, 4774, 4775, 4776,
       4777, 4779, 4780, 4782, 4785, 4786, 4788, 4791, 4793, 4794, 4797,
       4798, 4799, 4802, 4803, 4804, 4805, 4808, 4809, 4810, 4811, 4812,
       4813, 4814, 4829, 4831, 4832, 4833, 4838, 4839, 4842, 4845, 4846,
       4847, 4849, 4854, 4857, 4858, 4859, 4863, 4865, 4866, 4867, 4868,
       4872, 4873, 4874, 4876, 4880, 4881, 4885, 4886, 4888, 4889, 4890,
       4892, 4893, 4894, 4900, 4904, 4909, 4913, 4915, 4917, 4918, 4921,
       4923, 4924, 4925, 4926, 4927, 4930, 4935, 4936, 4945, 4947, 4948,
       4949, 4955, 4958, 4960, 4964, 4965, 4967, 4974, 4978, 4989, 4991,
       4993, 4995, 4998, 5002, 5005, 5008, 5009, 5014, 5017, 5024, 5031,
       5033, 5034, 5035, 5037, 5039, 5047, 5053, 5056, 5059, 5061, 5067,
       5082, 5087, 5088, 5093, 5096, 5097, 5101, 5105, 5111, 5113, 5115,
       5116, 5123, 5125, 5130, 5132, 5135, 5140, 5147, 5148, 5152, 5157,
       5162, 5179, 5182, 5191, 5193, 5195, 5196, 5202, 5203, 5207, 5217,
       5222, 5226, 5227, 5228, 5229, 5231, 5235, 5249, 5253, 5262, 5265,
       5283, 5292, 5293, 5303, 5307, 5310, 5323, 5338, 5362, 5363, 5367,
       5369, 5375, 5405, 5450, 5451, 5457, 5465, 5489, 5519, 5535, 5549,
       5554, 5599, 5615, 5628, 5697, 5709, 5826, 5894, 5951, 5970, 6056,
       6204])

In [62]:
len(movies["director_id"].unique())
# or 
movies["director_id"].nunique()

199

In [63]:
directors["id"].nunique()

2349

In [ ]:
# Check Movie director in directors dataset
movies["director_id"].isin(directors["id"])

# We have to insure that all must true

0       True
1       True
2       True
3       True
5       True
        ...
4736    True
4743    True
4748    True
4749    True
4768    True
Name: director_id, Length: 1465, dtype: bool

In [ ]:
np.all(movies["director_id"].isin(directors["id"])) # all are true

np.True_

In [69]:
data = movies.merge(directors,left_on="director_id",right_on="id",how="left")

In [70]:
data.head()

,id_x,budget,popularity,revenue,title,vote_average,vote_count,director_id,year,month,day,director_name,id_y,gender
0,43597,237000000,150,2787965087,Avatar,7.2,11800,4762,2009,Dec,Thursday,James Cameron,4762,Male
1,43598,300000000,139,961000000,Pirates of the Caribbean: At World's End,6.9,4500,4763,2007,May,Saturday,Gore Verbinski,4763,Male
2,43599,245000000,107,880674609,Spectre,6.3,4466,4764,2015,Oct,Monday,Sam Mendes,4764,Male
3,43600,250000000,112,1084939099,The Dark Knight Rises,7.6,9106,4765,2012,Jul,Monday,Christopher Nolan,4765,Male
4,43602,258000000,115,890871626,Spider-Man 3,5.9,3576,4767,2007,May,Tuesday,Sam Raimi,4767,Male

In [ ]:
# idx is movie id
# idy is director id

# Which col are redundant ? 
# director_id and idy

In [71]:
data.drop(["director_id","id_y"],axis=1,inplace=True)

In [72]:
data

,id_x,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender
0,43597,237000000,150,2787965087,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,Male
1,43598,300000000,139,961000000,Pirates of the Caribbean: At World's End,6.9,4500,2007,May,Saturday,Gore Verbinski,Male
2,43599,245000000,107,880674609,Spectre,6.3,4466,2015,Oct,Monday,Sam Mendes,Male
3,43600,250000000,112,1084939099,The Dark Knight Rises,7.6,9106,2012,Jul,Monday,Christopher Nolan,Male
4,43602,258000000,115,890871626,Spider-Man 3,5.9,3576,2007,May,Tuesday,Sam Raimi,Male
...,...,...,...,...,...,...,...,...,...,...,...,...
1460,48363,0,3,321952,The Last Waltz,7.9,64,1978,May,Monday,Martin Scorsese,Male
1461,48370,27000,19,3151130,Clerks,7.4,755,1994,Sep,Tuesday,Kevin Smith,Male
1462,48375,0,7,0,Rampage,6.0,131,2009,Aug,Friday,Uwe Boll,Male
1463,48376,0,3,0,Slacker,6.4,77,1990,Jul,Friday,Richard Linklater,Male
1464,48395,220000,14,2040920,El Mariachi,6.6,238,1992,Sep,Friday,Robert Rodriguez,NaN

In [73]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1465 entries, 0 to 1464
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id_x           1465 non-null   int64
 1   budget         1465 non-null   int64
 2   popularity     1465 non-null   int64
 3   revenue        1465 non-null   int64
 4   title          1465 non-null   str
 5   vote_average   1465 non-null   float64
 6   vote_count     1465 non-null   int64
 7   year           1465 non-null   int64
 8   month          1465 non-null   str
 9   day            1465 non-null   str
 10  director_name  1465 non-null   str
 11  gender         1341 non-null   str
dtypes: float64(1), int64(6), str(5)
memory usage: 137.5 KB

In [74]:
data.describe()

,id_x,budget,popularity,revenue,vote_average,vote_count,year
count,1465.000000,1.465000e+03,1465.000000,1.465000e+03,1465.000000,1465.000000,1465.000000
mean,45225.191126,4.802295e+07,30.855973,1.432539e+08,6.368191,1146.396587,2002.615017
std,1189.096396,4.935541e+07,34.845214,2.064918e+08,0.818033,1578.077438,8.680141
min,43597.000000,0.000000e+00,0.000000,0.000000e+00,3.000000,1.000000,1976.000000
25%,44236.000000,1.400000e+07,11.000000,1.738013e+07,5.900000,216.000000,1998.000000
50%,45022.000000,3.300000e+07,23.000000,7.578164e+07,6.400000,571.000000,2004.000000
75%,45990.000000,6.600000e+07,41.000000,1.792469e+08,6.900000,1387.000000,2009.000000
max,48395.000000,3.800000e+08,724.000000,2.787965e+09,8.300000,13752.000000,2016.000000

In [75]:
data.describe(include="object")

C:\Users\anura\AppData\Local\Temp\ipykernel_18108\460854327.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  data.describe(include="object")

         title month     day     director_name gender
count     1465  1465    1465              1465   1341
unique    1465    12       7               199      2
top     Avatar   Dec  Friday  Steven Spielberg   Male
freq         1   193     654                26   1309